listening-port=3478
fingerprint
use-auth-secret
static-auth-secret=1qjKjmQLEd149r0TWFIT0hbqLpmdyr6DuF
realm=turn.windoweropu.store
server-name=turn.windoweropu.store

no-cli
no-tls
no-dtls

external-ip=94.102.126.22

min-port=49160
max-port=49200

total-quota=100
bps-capacity=0
stale-nonce=600

log-file=stdout
simple-log