"""empty message

Revision ID: 990439a633e3
Revises: af2be2dbcc2b
Create Date: 2026-01-22 12:50:26.976167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990439a633e3'
down_revision: Union[str, None] = 'af2be2dbcc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('contact', sa.String(length=256), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'provider', name='unique_profile_provider')
    )
    op.create_index(op.f('ix_contacts_profile_id'), 'contacts', ['profile_id'], unique=False)
    op.add_column('profiles', sa.Column('date_birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'date_birthday')
    op.drop_index(op.f('ix_contacts_profile_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
