"""empty message

Revision ID: af2be2dbcc2b
Revises: 650d9eef8a60
Create Date: 2026-01-22 00:39:06.240808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af2be2dbcc2b'
down_revision: Union[str, None] = '650d9eef8a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatars', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('profiles', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'avatars')
    # ### end Alembic commands ###
